name: yaobinthen
favicon: null
layout_spectrum: 0.63189
typography_spectrum: 0.63908
title: 'yaobinthen | software development knowledge sharing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73797886-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#536b78'
    - '#accbe1'
    - '#7c98b3'
    - '#e5ebea'
    - '#3e2d54'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
