name: yaobinthen
favicon: null
layout_spectrum: 0.74528
typography_spectrum: 0.63908
title: 'yaobinthen | software development knowledge sharing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73797886-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#721817'
    - '#fa9f42'
    - '#0b6e4f'
    - '#e0e0e2'
    - '#98959e'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
