name: yaobinthen
favicon: null
layout_spectrum: 0.3595
typography_spectrum: 0.25589
title: 'yaobinthen | software development knowledge sharing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73797886-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#fafafa'
    - '#404040'
    - '#686868'
    - '#cacaca'
  brandStrength: 1
  lightness: 0.0567369784694165
  saturation: 0.4375
  rhythmicContrast: 0.90076405974105
purpose: []
