name: yaobinthen
favicon: null
layout_spectrum: 0.36795
typography_spectrum: 0.63908
title: 'yaobinthen | software development knowledge sharing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73797886-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00171f'
    - '#007ea7'
    - '#aca9b0'
    - '#5e6c71'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
