name: yaobinthen
favicon: null
layout_spectrum: 0.36795
typography_spectrum: 0.63908
title: 'yaobinthen | software development knowledge sharing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73797886-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbb13c'
    - '#2176ae'
    - '#57b8ff'
    - '#ffffff'
    - '#3e2d54'
  brandStrength: 0.75
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.90076405974105
purpose: []
